//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdBudget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseholdBudget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$2.
        /// </summary>
        internal static string ArchiveDirectoryRange {
            get {
                return ResourceManager.GetString("ArchiveDirectoryRange", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationWorksheetName {
            get {
                return ResourceManager.GetString("ConfigurationWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $M$2.
        /// </summary>
        internal static string DataListBottomRightRange {
            get {
                return ResourceManager.GetString("DataListBottomRightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIVOT_DATA.
        /// </summary>
        internal static string DataListObjectName {
            get {
                return ResourceManager.GetString("DataListObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1:$M$1.
        /// </summary>
        internal static string DataListObjectRange {
            get {
                return ResourceManager.GetString("DataListObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $M.
        /// </summary>
        internal static string DataListRightMostColumn {
            get {
                return ResourceManager.GetString("DataListRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1.
        /// </summary>
        internal static string DataListTopLeftRange {
            get {
                return ResourceManager.GetString("DataListTopLeftRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $J$2.
        /// </summary>
        internal static string DataWorksheetBottomRightRange {
            get {
                return ResourceManager.GetString("DataWorksheetBottomRightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKSHEET_.
        /// </summary>
        internal static string DataWorksheetName {
            get {
                return ResourceManager.GetString("DataWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1:$J$1.
        /// </summary>
        internal static string DataWorksheetObjectRange {
            get {
                return ResourceManager.GetString("DataWorksheetObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $J.
        /// </summary>
        internal static string DataWorksheetRightMostColumn {
            get {
                return ResourceManager.GetString("DataWorksheetRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1.
        /// </summary>
        internal static string DataWorksheetTopLeftRange {
            get {
                return ResourceManager.GetString("DataWorksheetTopLeftRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        internal static string DefaultArchiveDirectory {
            get {
                return ResourceManager.GetString("DefaultArchiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT_RESULTS.
        /// </summary>
        internal static string ImportResultsListObjectName {
            get {
                return ResourceManager.GetString("ImportResultsListObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1:$E$1.
        /// </summary>
        internal static string ImportResultsListObjectRange {
            get {
                return ResourceManager.GetString("ImportResultsListObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $E.
        /// </summary>
        internal static string ImportResultsRightMostColumn {
            get {
                return ResourceManager.GetString("ImportResultsRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1.
        /// </summary>
        internal static string ImportResultsTopLeftRange {
            get {
                return ResourceManager.GetString("ImportResultsTopLeftRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT RESULTS.
        /// </summary>
        internal static string ImportResultsWorksheetName {
            get {
                return ResourceManager.GetString("ImportResultsWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA.
        /// </summary>
        internal static string MasterDataWorksheetName {
            get {
                return ResourceManager.GetString("MasterDataWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string MaxSearchResults {
            get {
                return ResourceManager.GetString("MaxSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Budget.
        /// </summary>
        internal static string WorkbookNameValue {
            get {
                return ResourceManager.GetString("WorkbookNameValue", resourceCulture);
            }
        }
    }
}
