//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimSubCategories", "dimSubCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimSubCategories), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimDaysOfWeeks), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimMonths", "dimMonths", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimMonths), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimTypes", "dimTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimTypes), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimSubTypes", "dimSubTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimSubTypes), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_dimSubCategories_dimCategories", "dimSubCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.dimSubCategories), "dimCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimCategories), true)]
[assembly: EdmRelationshipAttribute("BudgetModel", "FK_factLineItems_dimPaymentMethods", "dimPaymentMethods", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HouseholdBudget.DataModel.dimPaymentMethods), "factLineItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HouseholdBudget.DataModel.factLineItems), true)]

#endregion

namespace HouseholdBudget.DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BudgetEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BudgetEntities object using the connection string found in the 'BudgetEntities' section of the application configuration file.
        /// </summary>
        public BudgetEntities() : base("name=BudgetEntities", "BudgetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BudgetEntities object.
        /// </summary>
        public BudgetEntities(string connectionString) : base(connectionString, "BudgetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BudgetEntities object.
        /// </summary>
        public BudgetEntities(EntityConnection connection) : base(connection, "BudgetEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimSubTypes> dimSubTypes
        {
            get
            {
                if ((_dimSubTypes == null))
                {
                    _dimSubTypes = base.CreateObjectSet<dimSubTypes>("dimSubTypes");
                }
                return _dimSubTypes;
            }
        }
        private ObjectSet<dimSubTypes> _dimSubTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimSubCategories> dimSubCategories
        {
            get
            {
                if ((_dimSubCategories == null))
                {
                    _dimSubCategories = base.CreateObjectSet<dimSubCategories>("dimSubCategories");
                }
                return _dimSubCategories;
            }
        }
        private ObjectSet<dimSubCategories> _dimSubCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimCategories> dimCategories
        {
            get
            {
                if ((_dimCategories == null))
                {
                    _dimCategories = base.CreateObjectSet<dimCategories>("dimCategories");
                }
                return _dimCategories;
            }
        }
        private ObjectSet<dimCategories> _dimCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimDaysOfWeeks> dimDaysOfWeeks
        {
            get
            {
                if ((_dimDaysOfWeeks == null))
                {
                    _dimDaysOfWeeks = base.CreateObjectSet<dimDaysOfWeeks>("dimDaysOfWeeks");
                }
                return _dimDaysOfWeeks;
            }
        }
        private ObjectSet<dimDaysOfWeeks> _dimDaysOfWeeks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimMonths> dimMonths
        {
            get
            {
                if ((_dimMonths == null))
                {
                    _dimMonths = base.CreateObjectSet<dimMonths>("dimMonths");
                }
                return _dimMonths;
            }
        }
        private ObjectSet<dimMonths> _dimMonths;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimTypes> dimTypes
        {
            get
            {
                if ((_dimTypes == null))
                {
                    _dimTypes = base.CreateObjectSet<dimTypes>("dimTypes");
                }
                return _dimTypes;
            }
        }
        private ObjectSet<dimTypes> _dimTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<factLineItems> factLineItems
        {
            get
            {
                if ((_factLineItems == null))
                {
                    _factLineItems = base.CreateObjectSet<factLineItems>("factLineItems");
                }
                return _factLineItems;
            }
        }
        private ObjectSet<factLineItems> _factLineItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dimPaymentMethods> dimPaymentMethods
        {
            get
            {
                if ((_dimPaymentMethods == null))
                {
                    _dimPaymentMethods = base.CreateObjectSet<dimPaymentMethods>("dimPaymentMethods");
                }
                return _dimPaymentMethods;
            }
        }
        private ObjectSet<dimPaymentMethods> _dimPaymentMethods;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimSubTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimSubTypes(dimSubTypes dimSubTypes)
        {
            base.AddObject("dimSubTypes", dimSubTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimSubCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimSubCategories(dimSubCategories dimSubCategories)
        {
            base.AddObject("dimSubCategories", dimSubCategories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimCategories(dimCategories dimCategories)
        {
            base.AddObject("dimCategories", dimCategories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimDaysOfWeeks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimDaysOfWeeks(dimDaysOfWeeks dimDaysOfWeeks)
        {
            base.AddObject("dimDaysOfWeeks", dimDaysOfWeeks);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimMonths EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimMonths(dimMonths dimMonths)
        {
            base.AddObject("dimMonths", dimMonths);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimTypes(dimTypes dimTypes)
        {
            base.AddObject("dimTypes", dimTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the factLineItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofactLineItems(factLineItems factLineItems)
        {
            base.AddObject("factLineItems", factLineItems);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dimPaymentMethods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodimPaymentMethods(dimPaymentMethods dimPaymentMethods)
        {
            base.AddObject("dimPaymentMethods", dimPaymentMethods);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimCategories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimCategories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimCategories object.
        /// </summary>
        /// <param name="categoryKey">Initial value of the CategoryKey property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static dimCategories CreatedimCategories(global::System.Guid categoryKey, global::System.String categoryName)
        {
            dimCategories dimCategories = new dimCategories();
            dimCategories.CategoryKey = categoryKey;
            dimCategories.CategoryName = categoryName;
            return dimCategories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CategoryKey
        {
            get
            {
                return _CategoryKey;
            }
            set
            {
                if (_CategoryKey != value)
                {
                    OnCategoryKeyChanging(value);
                    ReportPropertyChanging("CategoryKey");
                    _CategoryKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryKey");
                    OnCategoryKeyChanged();
                }
            }
        }
        private global::System.Guid _CategoryKey;
        partial void OnCategoryKeyChanging(global::System.Guid value);
        partial void OnCategoryKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_dimSubCategories_dimCategories", "dimSubCategories")]
        public EntityCollection<dimSubCategories> SubCategoriesInThisCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<dimSubCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimSubCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<dimSubCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimSubCategories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimDaysOfWeeks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimDaysOfWeeks : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimDaysOfWeeks object.
        /// </summary>
        /// <param name="dayId">Initial value of the DayId property.</param>
        /// <param name="dayName">Initial value of the DayName property.</param>
        public static dimDaysOfWeeks CreatedimDaysOfWeeks(global::System.Int16 dayId, global::System.String dayName)
        {
            dimDaysOfWeeks dimDaysOfWeeks = new dimDaysOfWeeks();
            dimDaysOfWeeks.DayId = dayId;
            dimDaysOfWeeks.DayName = dayName;
            return dimDaysOfWeeks;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DayId
        {
            get
            {
                return _DayId;
            }
            set
            {
                if (_DayId != value)
                {
                    OnDayIdChanging(value);
                    ReportPropertyChanging("DayId");
                    _DayId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DayId");
                    OnDayIdChanged();
                }
            }
        }
        private global::System.Int16 _DayId;
        partial void OnDayIdChanging(global::System.Int16 value);
        partial void OnDayIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DayName
        {
            get
            {
                return _DayName;
            }
            set
            {
                OnDayNameChanging(value);
                ReportPropertyChanging("DayName");
                _DayName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DayName");
                OnDayNameChanged();
            }
        }
        private global::System.String _DayName;
        partial void OnDayNameChanging(global::System.String value);
        partial void OnDayNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimDaysOfWeek", "factLineItems")]
        public EntityCollection<factLineItems> ItemsForThisDay
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "factLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimMonths")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimMonths : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimMonths object.
        /// </summary>
        /// <param name="monthId">Initial value of the MonthId property.</param>
        /// <param name="monthName">Initial value of the MonthName property.</param>
        public static dimMonths CreatedimMonths(global::System.Int16 monthId, global::System.String monthName)
        {
            dimMonths dimMonths = new dimMonths();
            dimMonths.MonthId = monthId;
            dimMonths.MonthName = monthName;
            return dimMonths;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 MonthId
        {
            get
            {
                return _MonthId;
            }
            set
            {
                if (_MonthId != value)
                {
                    OnMonthIdChanging(value);
                    ReportPropertyChanging("MonthId");
                    _MonthId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MonthId");
                    OnMonthIdChanged();
                }
            }
        }
        private global::System.Int16 _MonthId;
        partial void OnMonthIdChanging(global::System.Int16 value);
        partial void OnMonthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MonthName
        {
            get
            {
                return _MonthName;
            }
            set
            {
                OnMonthNameChanging(value);
                ReportPropertyChanging("MonthName");
                _MonthName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MonthName");
                OnMonthNameChanged();
            }
        }
        private global::System.String _MonthName;
        partial void OnMonthNameChanging(global::System.String value);
        partial void OnMonthNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimMonths", "factLineItems")]
        public EntityCollection<factLineItems> ItemsInThisMonth
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimMonths", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimMonths", "factLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimPaymentMethods")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimPaymentMethods : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimPaymentMethods object.
        /// </summary>
        /// <param name="paymentMethodKey">Initial value of the PaymentMethodKey property.</param>
        /// <param name="paymentMethod">Initial value of the PaymentMethod property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static dimPaymentMethods CreatedimPaymentMethods(global::System.Guid paymentMethodKey, global::System.String paymentMethod, global::System.Boolean isActive)
        {
            dimPaymentMethods dimPaymentMethods = new dimPaymentMethods();
            dimPaymentMethods.PaymentMethodKey = paymentMethodKey;
            dimPaymentMethods.PaymentMethod = paymentMethod;
            dimPaymentMethods.IsActive = isActive;
            return dimPaymentMethods;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PaymentMethodKey
        {
            get
            {
                return _PaymentMethodKey;
            }
            set
            {
                if (_PaymentMethodKey != value)
                {
                    OnPaymentMethodKeyChanging(value);
                    ReportPropertyChanging("PaymentMethodKey");
                    _PaymentMethodKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentMethodKey");
                    OnPaymentMethodKeyChanged();
                }
            }
        }
        private global::System.Guid _PaymentMethodKey;
        partial void OnPaymentMethodKeyChanging(global::System.Guid value);
        partial void OnPaymentMethodKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaymentMethod
        {
            get
            {
                return _PaymentMethod;
            }
            set
            {
                OnPaymentMethodChanging(value);
                ReportPropertyChanging("PaymentMethod");
                _PaymentMethod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PaymentMethod");
                OnPaymentMethodChanged();
            }
        }
        private global::System.String _PaymentMethod;
        partial void OnPaymentMethodChanging(global::System.String value);
        partial void OnPaymentMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimPaymentMethods", "factLineItems")]
        public EntityCollection<factLineItems> ItemsPaidWithThisMethod
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimPaymentMethods", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimPaymentMethods", "factLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimSubCategories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimSubCategories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimSubCategories object.
        /// </summary>
        /// <param name="subCategoryKey">Initial value of the SubCategoryKey property.</param>
        /// <param name="categoryKey">Initial value of the CategoryKey property.</param>
        /// <param name="subCategoryName">Initial value of the SubCategoryName property.</param>
        /// <param name="subCategoryPrefix">Initial value of the SubCategoryPrefix property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static dimSubCategories CreatedimSubCategories(global::System.Guid subCategoryKey, global::System.Guid categoryKey, global::System.String subCategoryName, global::System.String subCategoryPrefix, global::System.Boolean isActive)
        {
            dimSubCategories dimSubCategories = new dimSubCategories();
            dimSubCategories.SubCategoryKey = subCategoryKey;
            dimSubCategories.CategoryKey = categoryKey;
            dimSubCategories.SubCategoryName = subCategoryName;
            dimSubCategories.SubCategoryPrefix = subCategoryPrefix;
            dimSubCategories.IsActive = isActive;
            return dimSubCategories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SubCategoryKey
        {
            get
            {
                return _SubCategoryKey;
            }
            set
            {
                if (_SubCategoryKey != value)
                {
                    OnSubCategoryKeyChanging(value);
                    ReportPropertyChanging("SubCategoryKey");
                    _SubCategoryKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubCategoryKey");
                    OnSubCategoryKeyChanged();
                }
            }
        }
        private global::System.Guid _SubCategoryKey;
        partial void OnSubCategoryKeyChanging(global::System.Guid value);
        partial void OnSubCategoryKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CategoryKey
        {
            get
            {
                return _CategoryKey;
            }
            set
            {
                OnCategoryKeyChanging(value);
                ReportPropertyChanging("CategoryKey");
                _CategoryKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryKey");
                OnCategoryKeyChanged();
            }
        }
        private global::System.Guid _CategoryKey;
        partial void OnCategoryKeyChanging(global::System.Guid value);
        partial void OnCategoryKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubCategoryName
        {
            get
            {
                return _SubCategoryName;
            }
            set
            {
                OnSubCategoryNameChanging(value);
                ReportPropertyChanging("SubCategoryName");
                _SubCategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubCategoryName");
                OnSubCategoryNameChanged();
            }
        }
        private global::System.String _SubCategoryName;
        partial void OnSubCategoryNameChanging(global::System.String value);
        partial void OnSubCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubCategoryPrefix
        {
            get
            {
                return _SubCategoryPrefix;
            }
            set
            {
                OnSubCategoryPrefixChanging(value);
                ReportPropertyChanging("SubCategoryPrefix");
                _SubCategoryPrefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubCategoryPrefix");
                OnSubCategoryPrefixChanged();
            }
        }
        private global::System.String _SubCategoryPrefix;
        partial void OnSubCategoryPrefixChanging(global::System.String value);
        partial void OnSubCategoryPrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimSubCategories", "factLineItems")]
        public EntityCollection<factLineItems> ItemsInThisCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimSubCategories", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimSubCategories", "factLineItems", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_dimSubCategories_dimCategories", "dimCategories")]
        public dimCategories ParentCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimCategories> ParentCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimCategories>("BudgetModel.FK_dimSubCategories_dimCategories", "dimCategories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimSubTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimSubTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimSubTypes object.
        /// </summary>
        /// <param name="subTypeId">Initial value of the SubTypeId property.</param>
        /// <param name="subTypeName">Initial value of the SubTypeName property.</param>
        public static dimSubTypes CreatedimSubTypes(global::System.Int16 subTypeId, global::System.String subTypeName)
        {
            dimSubTypes dimSubTypes = new dimSubTypes();
            dimSubTypes.SubTypeId = subTypeId;
            dimSubTypes.SubTypeName = subTypeName;
            return dimSubTypes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SubTypeId
        {
            get
            {
                return _SubTypeId;
            }
            set
            {
                if (_SubTypeId != value)
                {
                    OnSubTypeIdChanging(value);
                    ReportPropertyChanging("SubTypeId");
                    _SubTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubTypeId");
                    OnSubTypeIdChanged();
                }
            }
        }
        private global::System.Int16 _SubTypeId;
        partial void OnSubTypeIdChanging(global::System.Int16 value);
        partial void OnSubTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubTypeName
        {
            get
            {
                return _SubTypeName;
            }
            set
            {
                OnSubTypeNameChanging(value);
                ReportPropertyChanging("SubTypeName");
                _SubTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubTypeName");
                OnSubTypeNameChanged();
            }
        }
        private global::System.String _SubTypeName;
        partial void OnSubTypeNameChanging(global::System.String value);
        partial void OnSubTypeNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimSubTypes", "factLineItems")]
        public EntityCollection<factLineItems> ItemsOfThisSubType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimSubTypes", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimSubTypes", "factLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="dimTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dimTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dimTypes object.
        /// </summary>
        /// <param name="typeId">Initial value of the TypeId property.</param>
        /// <param name="typeName">Initial value of the TypeName property.</param>
        public static dimTypes CreatedimTypes(global::System.Int32 typeId, global::System.String typeName)
        {
            dimTypes dimTypes = new dimTypes();
            dimTypes.TypeId = typeId;
            dimTypes.TypeName = typeName;
            return dimTypes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                if (_TypeId != value)
                {
                    OnTypeIdChanging(value);
                    ReportPropertyChanging("TypeId");
                    _TypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TypeId");
                    OnTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _TypeId;
        partial void OnTypeIdChanging(global::System.Int32 value);
        partial void OnTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TypeName
        {
            get
            {
                return _TypeName;
            }
            set
            {
                OnTypeNameChanging(value);
                ReportPropertyChanging("TypeName");
                _TypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TypeName");
                OnTypeNameChanged();
            }
        }
        private global::System.String _TypeName;
        partial void OnTypeNameChanging(global::System.String value);
        partial void OnTypeNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimTypes", "factLineItems")]
        public EntityCollection<factLineItems> ItemsOfThisType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimTypes", "factLineItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<factLineItems>("BudgetModel.FK_factLineItems_dimTypes", "factLineItems", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BudgetModel", Name="factLineItems")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class factLineItems : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new factLineItems object.
        /// </summary>
        /// <param name="uniqueKey">Initial value of the UniqueKey property.</param>
        /// <param name="monthId">Initial value of the MonthId property.</param>
        /// <param name="dayOfMonthId">Initial value of the DayOfMonthId property.</param>
        /// <param name="dayOfWeekId">Initial value of the DayOfWeekId property.</param>
        /// <param name="yearId">Initial value of the YearId property.</param>
        /// <param name="categoryKey">Initial value of the CategoryKey property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="typeId">Initial value of the TypeId property.</param>
        /// <param name="quarterId">Initial value of the QuarterId property.</param>
        /// <param name="subTypeId">Initial value of the SubTypeId property.</param>
        /// <param name="paymentMethodId">Initial value of the PaymentMethodId property.</param>
        public static factLineItems CreatefactLineItems(global::System.Guid uniqueKey, global::System.Int16 monthId, global::System.Int16 dayOfMonthId, global::System.Int16 dayOfWeekId, global::System.Int32 yearId, global::System.Guid categoryKey, global::System.String description, global::System.Decimal amount, global::System.Int32 typeId, global::System.Int16 quarterId, global::System.Int16 subTypeId, global::System.Guid paymentMethodId)
        {
            factLineItems factLineItems = new factLineItems();
            factLineItems.UniqueKey = uniqueKey;
            factLineItems.MonthId = monthId;
            factLineItems.DayOfMonthId = dayOfMonthId;
            factLineItems.DayOfWeekId = dayOfWeekId;
            factLineItems.YearId = yearId;
            factLineItems.CategoryKey = categoryKey;
            factLineItems.Description = description;
            factLineItems.Amount = amount;
            factLineItems.TypeId = typeId;
            factLineItems.QuarterId = quarterId;
            factLineItems.SubTypeId = subTypeId;
            factLineItems.PaymentMethodId = paymentMethodId;
            return factLineItems;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UniqueKey
        {
            get
            {
                return _UniqueKey;
            }
            set
            {
                if (_UniqueKey != value)
                {
                    OnUniqueKeyChanging(value);
                    ReportPropertyChanging("UniqueKey");
                    _UniqueKey = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UniqueKey");
                    OnUniqueKeyChanged();
                }
            }
        }
        private global::System.Guid _UniqueKey;
        partial void OnUniqueKeyChanging(global::System.Guid value);
        partial void OnUniqueKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 MonthId
        {
            get
            {
                return _MonthId;
            }
            set
            {
                OnMonthIdChanging(value);
                ReportPropertyChanging("MonthId");
                _MonthId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonthId");
                OnMonthIdChanged();
            }
        }
        private global::System.Int16 _MonthId;
        partial void OnMonthIdChanging(global::System.Int16 value);
        partial void OnMonthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DayOfMonthId
        {
            get
            {
                return _DayOfMonthId;
            }
            set
            {
                OnDayOfMonthIdChanging(value);
                ReportPropertyChanging("DayOfMonthId");
                _DayOfMonthId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayOfMonthId");
                OnDayOfMonthIdChanged();
            }
        }
        private global::System.Int16 _DayOfMonthId;
        partial void OnDayOfMonthIdChanging(global::System.Int16 value);
        partial void OnDayOfMonthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 DayOfWeekId
        {
            get
            {
                return _DayOfWeekId;
            }
            set
            {
                OnDayOfWeekIdChanging(value);
                ReportPropertyChanging("DayOfWeekId");
                _DayOfWeekId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DayOfWeekId");
                OnDayOfWeekIdChanged();
            }
        }
        private global::System.Int16 _DayOfWeekId;
        partial void OnDayOfWeekIdChanging(global::System.Int16 value);
        partial void OnDayOfWeekIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 YearId
        {
            get
            {
                return _YearId;
            }
            set
            {
                OnYearIdChanging(value);
                ReportPropertyChanging("YearId");
                _YearId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YearId");
                OnYearIdChanged();
            }
        }
        private global::System.Int32 _YearId;
        partial void OnYearIdChanging(global::System.Int32 value);
        partial void OnYearIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CategoryKey
        {
            get
            {
                return _CategoryKey;
            }
            set
            {
                OnCategoryKeyChanging(value);
                ReportPropertyChanging("CategoryKey");
                _CategoryKey = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryKey");
                OnCategoryKeyChanged();
            }
        }
        private global::System.Guid _CategoryKey;
        partial void OnCategoryKeyChanging(global::System.Guid value);
        partial void OnCategoryKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private global::System.Int32 _TypeId;
        partial void OnTypeIdChanging(global::System.Int32 value);
        partial void OnTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 QuarterId
        {
            get
            {
                return _QuarterId;
            }
            set
            {
                OnQuarterIdChanging(value);
                ReportPropertyChanging("QuarterId");
                _QuarterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuarterId");
                OnQuarterIdChanged();
            }
        }
        private global::System.Int16 _QuarterId;
        partial void OnQuarterIdChanging(global::System.Int16 value);
        partial void OnQuarterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SubTypeId
        {
            get
            {
                return _SubTypeId;
            }
            set
            {
                OnSubTypeIdChanging(value);
                ReportPropertyChanging("SubTypeId");
                _SubTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubTypeId");
                OnSubTypeIdChanged();
            }
        }
        private global::System.Int16 _SubTypeId;
        partial void OnSubTypeIdChanging(global::System.Int16 value);
        partial void OnSubTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PaymentMethodId
        {
            get
            {
                return _PaymentMethodId;
            }
            set
            {
                OnPaymentMethodIdChanging(value);
                ReportPropertyChanging("PaymentMethodId");
                _PaymentMethodId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentMethodId");
                OnPaymentMethodIdChanged();
            }
        }
        private global::System.Guid _PaymentMethodId;
        partial void OnPaymentMethodIdChanging(global::System.Guid value);
        partial void OnPaymentMethodIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimSubCategories", "dimSubCategories")]
        public dimSubCategories Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubCategories>("BudgetModel.FK_factLineItems_dimSubCategories", "dimSubCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubCategories>("BudgetModel.FK_factLineItems_dimSubCategories", "dimSubCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimSubCategories> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubCategories>("BudgetModel.FK_factLineItems_dimSubCategories", "dimSubCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimSubCategories>("BudgetModel.FK_factLineItems_dimSubCategories", "dimSubCategories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks")]
        public dimDaysOfWeeks DayOfWeek
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimDaysOfWeeks>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimDaysOfWeeks>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimDaysOfWeeks> DayOfWeekReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimDaysOfWeeks>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimDaysOfWeeks>("BudgetModel.FK_factLineItems_dimDaysOfWeek", "dimDaysOfWeeks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimMonths", "dimMonths")]
        public dimMonths Month
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimMonths>("BudgetModel.FK_factLineItems_dimMonths", "dimMonths").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimMonths>("BudgetModel.FK_factLineItems_dimMonths", "dimMonths").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimMonths> MonthReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimMonths>("BudgetModel.FK_factLineItems_dimMonths", "dimMonths");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimMonths>("BudgetModel.FK_factLineItems_dimMonths", "dimMonths", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimTypes", "dimTypes")]
        public dimTypes Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimTypes>("BudgetModel.FK_factLineItems_dimTypes", "dimTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimTypes>("BudgetModel.FK_factLineItems_dimTypes", "dimTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimTypes> TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimTypes>("BudgetModel.FK_factLineItems_dimTypes", "dimTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimTypes>("BudgetModel.FK_factLineItems_dimTypes", "dimTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimSubTypes", "dimSubTypes")]
        public dimSubTypes SubType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubTypes>("BudgetModel.FK_factLineItems_dimSubTypes", "dimSubTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubTypes>("BudgetModel.FK_factLineItems_dimSubTypes", "dimSubTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimSubTypes> SubTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimSubTypes>("BudgetModel.FK_factLineItems_dimSubTypes", "dimSubTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimSubTypes>("BudgetModel.FK_factLineItems_dimSubTypes", "dimSubTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BudgetModel", "FK_factLineItems_dimPaymentMethods", "dimPaymentMethods")]
        public dimPaymentMethods PaymentMethod
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimPaymentMethods>("BudgetModel.FK_factLineItems_dimPaymentMethods", "dimPaymentMethods").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimPaymentMethods>("BudgetModel.FK_factLineItems_dimPaymentMethods", "dimPaymentMethods").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<dimPaymentMethods> PaymentMethodReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<dimPaymentMethods>("BudgetModel.FK_factLineItems_dimPaymentMethods", "dimPaymentMethods");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<dimPaymentMethods>("BudgetModel.FK_factLineItems_dimPaymentMethods", "dimPaymentMethods", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
