//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudget.AddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FamilyBudget.AddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationWorksheetName {
            get {
                return ResourceManager.GetString("ConfigurationWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Q$2.
        /// </summary>
        internal static string DataListBottomRightRange {
            get {
                return ResourceManager.GetString("DataListBottomRightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIVOT_DATA.
        /// </summary>
        internal static string DataListObjectName {
            get {
                return ResourceManager.GetString("DataListObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1:$Q$1.
        /// </summary>
        internal static string DataListObjectRange {
            get {
                return ResourceManager.GetString("DataListObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Q.
        /// </summary>
        internal static string DataListRightMostColumn {
            get {
                return ResourceManager.GetString("DataListRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1.
        /// </summary>
        internal static string DataListTopLeftRange {
            get {
                return ResourceManager.GetString("DataListTopLeftRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $J$2.
        /// </summary>
        internal static string DataWorksheetBottomRightRange {
            get {
                return ResourceManager.GetString("DataWorksheetBottomRightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKSHEET_.
        /// </summary>
        internal static string DataWorksheetName {
            get {
                return ResourceManager.GetString("DataWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1:$J$1.
        /// </summary>
        internal static string DataWorksheetObjectRange {
            get {
                return ResourceManager.GetString("DataWorksheetObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $J.
        /// </summary>
        internal static string DataWorksheetRightMostColumn {
            get {
                return ResourceManager.GetString("DataWorksheetRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $B$1.
        /// </summary>
        internal static string DataWorksheetTopLeftRange {
            get {
                return ResourceManager.GetString("DataWorksheetTopLeftRange", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA.
        /// </summary>
        internal static string MasterDataWorksheetName {
            get {
                return ResourceManager.GetString("MasterDataWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string MaxSearchResults {
            get {
                return ResourceManager.GetString("MaxSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBCATEGORIES.
        /// </summary>
        internal static string SubCategoriesDataWorksheetName {
            get {
                return ResourceManager.GetString("SubCategoriesDataWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $D$2.
        /// </summary>
        internal static string SubCategoriesListBottomRightRange {
            get {
                return ResourceManager.GetString("SubCategoriesListBottomRightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIVOT_SUBCATEGORIES.
        /// </summary>
        internal static string SubCategoriesListObjectName {
            get {
                return ResourceManager.GetString("SubCategoriesListObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1:$D$1.
        /// </summary>
        internal static string SubCategoriesListObjectRange {
            get {
                return ResourceManager.GetString("SubCategoriesListObjectRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $D.
        /// </summary>
        internal static string SubCategoriesListRightMostColumn {
            get {
                return ResourceManager.GetString("SubCategoriesListRightMostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $A$1.
        /// </summary>
        internal static string SubCategoriesListTopLeftRange {
            get {
                return ResourceManager.GetString("SubCategoriesListTopLeftRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Budget.
        /// </summary>
        internal static string WorkbookNameValue {
            get {
                return ResourceManager.GetString("WorkbookNameValue", resourceCulture);
            }
        }
    }
}
